### PR TITLE
Create `projectInfo` component, fix project info data updates

### LINKED ISSUE #588: Frontend: Project info is absent after page reloading
At the initial state all fields are `N/A`, however DB contain all necessary information

After clicking to the `edit` button and then to `cancel`, information appears:

### PR DESCRIPTION
**Pull request by petertrr**
* Create `projectInfo` component
* Store project in state of ProjectView
* Store draft project in state of `projectInfo`
* Only send request for update if project has actually changed

Closes #588

### CODE REVIEW

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectInfo.kt [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+
+import org.cqfn.save.entities.Project
+import org.cqfn.save.frontend.externals.fontawesome.faCheck
+import org.cqfn.save.frontend.externals.fontawesome.faTimesCircle
+import org.cqfn.save.frontend.externals.fontawesome.fontAwesomeIcon
+
+import react.FC
+import react.Props
+import react.dom.html.InputType
+import react.dom.html.ReactHTML.button
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/basic/ProjectInfo.kt:17]: `react.FC` rather than `react.fc` and DOM elements from `react.dom.html.ReactHTML` is a new kotlin-react API, which uses builders without `attrs`

**Review by akuleshov7 — APPROVED** [review]
