### PR TITLE
Bugfix for OrganizationSettingsMenu

### LINKED ISSUE #730: 404 at organizationSettingsMenu
Wrong url is used in requests:
`https://saveourtool.com/api/v1/organizations//users`

### PR DESCRIPTION
**Pull request by sanyavertolet**
This PR closes #730.

### What's done:
- [x] Fixed a bug with OrganizationSettingsMenu: now passing organizationName to OrganizationSettingsMenu

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]
quite easy

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt [hunk 1]
```diff
@@ -434,8 +434,8 @@ class OrganizationView : AbstractView<OrganizationProps, OrganizationViewState>(
 
     private fun RBuilder.renderSettings() {
         child(organizationSettingsMenu) {
-            attrs.organization = state.organization!!
-            attrs.selfRole = Role.SUPER_ADMIN
+            attrs.organizationName = props.organizationName
+            attrs.selfRole = Role.VIEWER
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt:438]: I can see that this prop is not used anywhere, is it needed?

**Comment by akuleshov7** [comment]
BUT you need to test the following SCENARIO: 
1) request the organization with a FAKE name: BLABLA
2) see the result

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt (hunk 1 above)
Comment (akuleshov7) [reply save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt:438]: what is the `attrs.selfRole`

Comment (sanyavertolet) [reply save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/OrganizationView.kt:438]: It used to be useful but now we do not need It. Removed it from both project and organization.

**Review by petertrr — APPROVED** [review]
