### PR TITLE
Fix renovate config

### LINKED ISSUE #548: Action Required: Fix Renovate Configuration
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Location: `renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: `packageRules[2]: packageRules cannot combine both matchUpdateTypes and allowedVersions. Rule: {"matchManagers":["gradle"],"matchPackagePatterns":["^org\\.springframework\\.boot\\:"],"allowedVersions":"!/2\\.7\\.5/","matchUpdateTypes":["minor","patch"],"groupName":"all non-major dependencies (except core Kotlin)","groupSlug":"all-minor-patch"}, packageRules[3]: packageRules cannot combine both matchUpdateTypes and allowedVersions. Rule: {"matchManagers":["gradle"],"matchPackagePatterns":["^org\\.cqfn\\.diktat\\:diktat-gradle-plugin"],"allowedVersions":"!/1\\.2\\.4\\.2/","matchUpdateTypes":["minor","patch"],"groupName":"all non-major dependencies (except core Kotlin)","groupSlug":"all-minor-patch"}`

### PR DESCRIPTION
**Pull request by petertrr**
Closes #548

### CODE REVIEW

File: buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt [hunk 1]
```diff
@@ -109,7 +109,7 @@ fun Project.createStackDeployTask(profile: String) {
                 ""
             } +
                 " save"
-        commandLine("bash", "-c", "'$composeCmd | $stackCmd'")
+        commandLine("bash", "-c", "$composeCmd | $stackCmd")
```
Comment (petertrr) [inline buildSrc/src/main/kotlin/org/cqfn/save/buildutils/DockerStackConfiguration.kt:112]: This is a hotfix for #547. JavaExec passes these strings directly into `argv`, so single quotes are not executed by bash and cause command to fail.

**Review by kgevorkyan — APPROVED** [review]
