### PR TITLE
Display proper message for unauthenticated access

### LINKED ISSUE #626: Authorization: improvements
1) when something goes wrong with authorization providers (Github/Codehub) - user should not see a blank page with an error (it should be handled in a proper way)

2) if user does not has a permission (for example - not authorised to see some project or even was not logged in) we should not silently redirect him to the login page. For user it looks like a bug.

### PR DESCRIPTION
**Pull request by petertrr**
* Frontend: Add separate handling of 401 responses in error modal
* Gateway: display error page if OAuth2 login attempt throws exception

image

Closes #626

### CODE REVIEW

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt [hunk 1]
```diff
@@ -116,12 +116,11 @@ suspend fun WithRequestStatusContext.post(
 internal fun Component<*, *>.classComponentResponseHandler(
     response: Response
 ) {
-    val isUnauthorized = response.status == 401.toShort()
     // dirty hack to determine whether this component contains `setResponse` in its context.
     // If we add another context with a function, this logic will break.
     val hasResponseContext = this.asDynamic().context is Function<*>
-    if (isUnauthorized || !hasResponseContext) {
-        redirectResponseHandler(response)
+    if (!hasResponseContext) {
```
Comment (kgevorkyan) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt:122]: Why do we need `noop` here, while it just returns `Unit`?

Could it be just like this, without else branch?

```suggestion
    if (hasResponseContext) {
        this.unsafeCast<Component<*, *>>().withModalResponseHandler(response)
    }
```

**Review by kgevorkyan — APPROVED** [review]

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt (hunk 1 above)
Comment (petertrr) [reply save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/RequestUtils.kt:122]: Yes, that makes sense, even though we don't have a valid fallback solution now. But anyway, we should always check that all class components have correct context type.
